dubbo:
    application:
        name: dubbo_provider
    protocol:
        name: dubbo
        port: -1
#    配置注册中心
    registry:
        id: zk-registry
        address: zookeeper://10.58.120.200:2181
#  config-center:
#    address: zookeeper://localhost:2181
#  metadata-report:
#    address: zookeeper://localhost:2181
server:
    port: 8081
